name: Enforce Semantic Pull Request Titles

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Format
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const allowedTypes = ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert'];
            const regex = /^\s*(?<type>\w+)\((?<scope>\w+)\):\s*(?<ticket>\[UNITY-\d+\])\s+(?<description>.+)$/;
            const match = regex.exec(title);

            if (!match) {
              throw new Error('PR title must follow the format: type(scope): [UNITY-XXXX] Description');
            }

            const { type, scope, ticket } = match.groups;

            // Check if type is valid
            if (!allowedTypes.includes(type)) {
              throw new Error(`Type "${type}" is not one of the allowed types (e.g., feat, fix, docs).`);
            }

            // Check if scope is present (required by configuration)
            if (!scope) {
              throw new Error('A scope is required in the PR title (e.g., feat(api):).');
            }

            // Check if ticket number is present
            if (!ticket || !/^\[UNITY-\d+\]$/.test(ticket)) {
              throw new Error('A UNITY ticket number is required in the PR title (e.g., [UNITY-1234]).');
            }

  triage:
    needs: validate-pr-title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: false

  size-label:
    needs: validate-pr-title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "10": "XS",
              "100": "S",
              "250": "M",
              "500": "L",
              "1000": "XL",
              "2000": "XXL"
            }

  unity-specific-labels:
    needs: validate-pr-title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Label Unity-specific changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: changedFiles } = await github.rest.pulls.listFiles({
              ...context.repo,
              pull_number: context.issue.number,
            });

            const filePaths = changedFiles.map(file => file.filename);

            const labelMap = {
              'Assets/': 'unity-assets',
              'ProjectSettings/': 'unity-settings',
              'Packages/': 'unity-packages',
              'Assets/Convai/Editor/': 'unity-editor',
              'Assets/Convai/Plugins/': 'unity-plugins'
            };

            const labelsToAdd = Object.entries(labelMap)
              .filter(([dir]) => filePaths.some(file => file.startsWith(dir)))
              .map(([, label]) => label);

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }